name: Varo
version: 1.0
author: deroq
main: net.howtobedwars.varo.Varo
commands:
  team:
  resetTimeOver:
  resetTime:
  addSpawn:
  start:
  revive:
  cps:
  broadcast:
  seen:
  toggledamage:
  toggleblockbreak:
  teamchat:
    aliases: [tc]